### ISSUE TITLE
Version published as NPM package is broken

### ISSUE THREAD

**Issue by cocowalla** [VandeurenGlenn/gulp-append#6]
Including `var append = require('gulp-append');` in a gulpfile results in this when attempting to execute anything:

`C:\MyDir\node_modules\gulp-append\lib\append.js:3
const {add, update} = require('./data-handler');
      ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\MyDir\node_modules\gulp-append\lib\index.js:4:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)`

**Comment by VandeurenGlenn** [comment]
Hi @cocowalla, this is  probably the same issue as #5, I'm planning to fix this in the weekend.
